@baseUrl = http://localhost:100/api/v1

### GET drivers
GET {{baseUrl}}/driver

### CREATE location
POST {{baseUrl}}/location/pla HTTP/1.1
Content-Type: application/json

{
    "ID": "pla",
    "address": "calle 9 #331 arcos",
    "coordinates": {
        "latitud": 20.920236508496956,
        "longitud": 89.66749090568848
    },
    "coordinates_delta": {
        "latitud": 20.921236508496956,
        "longitud": 89.66849090568848
    },
    "name": "papeleria los angelitos"
}

### GET locations
GET {{baseUrl}}/location

### GET a location
GET {{baseUrl}}/location/pla

### DELETE a location
DELETE  {{baseUrl}}/location/plas

### UPDATE trip
PUT {{baseUrl}}/location/pla HTTP/1.1
Content-Type: application/json

{
    "name": "papeleria los angelitos azules"
}