@baseUrl = http://localhost:100/api/v1

### GET drivers
GET {{baseUrl}}/driver

### CREATE location
POST {{baseUrl}}/location HTTP/1.1
Content-Type: application/json

{
    "name": "Lavanderia multiversos",
    "address": "calle 888 #222 Piedra de agua",
    "coordinates": {
        "latitud": 20.920236508496956,
        "longitud": -89.66749090568848
    },
    "coordinates_delta": {
        "latitud": 20.921236508496956,
        "longitud": -89.66849090568848
    }    
}

### GET locations
GET {{baseUrl}}/location

### GET a location
GET {{baseUrl}}/location/qUPqUoqgTGXEZEndx623

### DELETE a location
DELETE  {{baseUrl}}/location/nXbymiwVgpW4TMrm1TO9

### UPDATE trip
PUT {{baseUrl}}/location/kdaadsa HTTP/1.1
Content-Type: application/json

{
    "name": "papeleria los angelitos azules"
}