@localURL = http://localhost:80/api/v1
@BaseURL = http://34.234.66.51/api/v1

#### getClients
GET {{localURL}}/travelType

#### getTrips
GET {{localURL}}/driver

GET {{localURL}}/client

GET {{localURL}}/client

#### CreateClient
POST {{localURL}}/driver/ 

{
    "body": {
        "name": "cepillin",
        "last_name": "perez",
        "email": "nombre@correo.com",
        "password": "nombre@correo.com",
        "phone_number": "1234567890",
        "address": "direccion",
        "license_plate": "1234567890",
        "vehicle_color": "rojo",
    }
}

### getClient
GET {{localURL}}/client/A5MeSG9X5o0u9kBtF0J7

### updateClient
PUT {{localURL}}/client/A5MeSG9X5o0u9kBtF0J7 HTTP/1.1
Content-Type: application/json
    
    {
        "nombre": "cepillin",
        "apellidos": "perez",
        "correo": ""
    }

### deleteClient
DELETE {{BaseURL}}/driver/65a19ee889c708e2b13e0ddf

#### getDrivers
GET {{BaseURL}}/driver/

#### getDriver
GET {{BaseURL}}/driver/cVWC1Rard91gIRqzTQd0

#### getTrips
//GET {{BaseURL}}/trip/
GET {{localURL}}/trip/

###getTrip by id
GET {{BaseURL}}/trip/3gVBCjoa5eVcucmWALQX

#### postLocation
POST {{localURL}}/trip/

{
    "latitude": 1.0,
    "longitude": 1.0,
    "driver_id": "cVWC1Rard91gIRqzTQd0",
    "client_id": "aoVkXUKKB8LSt48jcRWc",
    "timestamp": "2019-01-01T00:00:00Z",
    "pickup_adress": "Rua 1",
    "dropoff_adress": "Rua 2",
    "pickup_id": "1",
    "dropoff_id": "2",
    "started_at": "2019-01-01T00:00:00Z",
    "finished_at": "2019-01-01T00:20:00Z",
    "fee": 15.0,
    "status": "requested",

}

#### PostLogin
POST {{BaseURL}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "asaf",
    "password": "123456"
}

#### getFees
GET {{localURL}}/fee

#### getFee by id
GET {{localURL}}/fee/8SAct55eAFFMyP8xgHxN

